### ISSUE TITLE
what is the "vcf" module?

### ISSUE THREAD

**Issue by NMUzhoujun** [vgteam/sv-genotyping-paper#14]
Hello,

I am running the "vcf-add-bed-seqs.py"
However, it doesn't work due to the lack "vcf" module
Where can I get it?

Thanks!

**Comment by vanhoan310** [comment]
Do you know how to install it? I tried to install PyVCF but it does not work.

**Comment by NMUzhoujun** [comment]
That's truly the problem I came across before and I have not addressed this problem till now. 
I directly used the SV graph the authors constructed and  skipped this procedure.
